songs = ['[Mariah Carey - All I Want For Christmas Is You](https://www.youtube.com/watch?v=yXQViqx6GMY)',
'[Wham! - Last Christmas](https://www.youtube.com/watch?v=E8gmARGvPlI)',
'[Pentatonix - Carol of the Bells](https://www.youtube.com/watch?v=WSUFzC6_fp8)',
'[Dean Martin - Let it Snow!](https://www.youtube.com/watch?v=mN7LW0Y00kE)',
'[Mariah Carey - O Holy Night](https://www.youtube.com/watch?v=BEJmP8T07JU)',
'[Andy Williams - It\'s The Most Wonderful Time Of The Year](https://www.youtube.com/watch?v=gFtb3EtjEic)',
'[Brenda Lee - Rockin\' Around The Christmas Tree Lyrics](https://www.youtube.com/watch?v=t3HJgCcSUqQ)',
'[Bobby Helms - Jingle Bell Rock](https://www.youtube.com/watch?v=itcMLwMEeMQ)',
'[Paul McCartney - Wonderful Christmas Time](https://www.youtube.com/watch?v=V9BZDpni56Y&list=PLWN1djuBEKCnEDqRgvMKKs8qnmiIOck2L&index=22)',
'[Bing Crosby - Mele Kalikimaka](https://www.youtube.com/watch?v=hEvGKUXW0iI)',
'[Jackson 5 - Santa Claus Is Comin\' To Town](https://www.youtube.com/watch?v=gmUW2pVAopc)',
'[Mel Torme - Have Yourself A Merry Little Christmas](https://www.youtube.com/watch?v=wt6Nd8Br50I)',
'[Stevie Wonder - What Christmas Means To Me](https://www.youtube.com/watch?v=wtgGBgpNcIo)',
'[Johnny Mathis - It\'s Beginning To Look Alot Like Christmas](https://www.youtube.com/watch?v=ZIfsWHqfWkI)',
'[Alvin & The Chipmunks - Christmas don\'t be late](https://www.youtube.com/watch?v=VUIAkGLbSNc)',
'[Amy Winehouse - I Saw Mommy Kissing Santa Claus](https://www.youtube.com/watch?v=Ta2TQkZ9PIA)',
'[Charles Brown - Please Come Home For Christmas](https://www.youtube.com/watch?v=FWoKgG8u1k0)',
'[Amy Grant - Sleigh Ride](https://www.youtube.com/watch?v=UsnrNa9bH0w)',
'[Sufjan Stevens - I\'ll Be Home For Christmas](https://www.youtube.com/watch?v=dNUbEDPWrvw)',
'[Bing Crosby - Rudolph The Red-Nosed Reindeer](https://www.youtube.com/watch?v=78c7vDFt6G8)',
'[John Legend & Kelly Clarkson - Baby, It\'s Cold Outside](https://www.youtube.com/watch?v=DlMP7FGYJmk)',
'[Jackson 5 - Frosty the Snowman](https://www.youtube.com/watch?v=qAE9neuV15g)',
'[Eartha Kitt - Santa Baby](https://www.youtube.com/watch?v=Mk_GmhD053E)',
'[Jose Feliciano - Feliz Navidad](https://www.youtube.com/watch?v=RTtc2pM1boE)',
'[Michael Bublé - It\'s Beginning To Look A Lot Like Christmas](https://www.youtube.com/watch?v=QJ5DOWPGxwg)',
'[Bing Crosby - Do You Hear What I Hear](https://www.youtube.com/watch?v=FhTnDaEmA5k)']
